// Persisted schema values stay in English so existing essays and external JSON remain compatible.
const labels: Record<string, string> = {
  Opinion: "观点题",
  Discussion: "讨论题",
  "Advantages / Disadvantages": "利弊题",
  "Problem / Solution": "问题与解决方案",
  "Two-part Question": "双问题",
  Culture: "文化",
  Education: "教育",
  Government: "政府",
  Environment: "环境",
  Technology: "科技",
  Crime: "犯罪",
  Work: "工作",
  Health: "健康",
  Media: "媒体",
  Society: "社会",
  Transport: "交通",
  Globalisation: "全球化",
  Family: "家庭",
  "Task Understanding": "理解题意",
  "Position Clarity": "立场清晰度",
  "Idea Development": "观点展开",
  "Supporting Detail": "具体论据",
  "Logical Organisation": "逻辑组织",
  "Vocabulary Use": "词汇运用",
  "Grammar Accuracy": "语法准确性",
  "Sentence Range": "句式多样性",
  "Task Response": "任务回应",
  "Coherence and Cohesion": "连贯与衔接",
  "Lexical Resource": "词汇资源",
  "Grammatical Range and Accuracy": "语法多样性与准确性",
  Spelling: "拼写",
  Capitalization: "大小写",
  Article: "冠词",
  "Singular/Plural": "单复数",
  "Subject-Verb Agreement": "主谓一致",
  Tense: "时态",
  Preposition: "介词",
  Pronoun: "代词",
  "Word Form": "词形",
  "Word Choice": "选词",
  Collocation: "搭配",
  "Sentence Structure": "句子结构",
  "Sentence Fragment": "句子残缺",
  "Run-on Sentence": "句子粘连",
  Punctuation: "标点",
  Repetition: "重复表达",
  Vocabulary: "词汇",
  Introduction: "引言",
  Conclusion: "结论",
  "Body Paragraph": "主体段",
  "Full Essay": "完整作文",
  "Quick Practice": "段落练习",
  Exam: "考试原稿",
  Revision: "修订版",
  Rewrite: "重新写作",
  Strength: "优点",
  "Useful Expression": "实用表达",
  Upgrade: "表达优化",
  Student: "来自原文",
  Suggested: "建议表达",
  Learning: "学习中",
  Mastered: "已掌握",
  All: "全部",
  High: "高",
  Medium: "中",
  Problems: "待改进",
  Strengths: "值得保留",
  Upgrades: "表达优化",
  Expressions: "实用表达",
  Band: "预估分数",
  Violations: "离开次数",
  taskUnderstanding: "理解题意",
  positionClarity: "立场清晰度",
  ideaDevelopment: "观点展开",
  supportingDetail: "具体论据",
  logicalOrganisation: "逻辑组织",
  vocabularyUse: "词汇运用",
  grammarAccuracy: "语法准确性",
  sentenceRange: "句式多样性",
  taskResponse: "任务回应",
  coherenceCohesion: "连贯与衔接",
  lexicalResource: "词汇资源",
  grammaticalRangeAccuracy: "语法多样性与准确性",
};
export const zh = (value: string | null | undefined): string =>
  value ? (labels[value] ?? value) : "";
